sudo: false
os:
  - linux
  - osx
  - windows
language: node_js
node_js:
  - '10'
  - '12'
  - '14'
  - '16'
install:
  - npm install
script:
  - npm run cov
after_script:
  - tap --coverage-report=text-lcov > coverage.lcov && codecov --disable=gcov